### PR TITLE
Nitro wrapkeytofile

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
upstream: https://github.com/trussed-dev/trussed/pull/115

**Review by robin-nitrokey — APPROVED** [review]
I would call it `wrap_key_to_file`/`unwrap_key_from_file`, otherwise looks good to me.

**Comment by sosthene-nitrokey** [comment]
This naming is indeed much better, I'll rename them

**Comment by sosthene-nitrokey** [comment]
This naming is indeed much better, I'll rename them

**Comment by sosthene-nitrokey** [comment]
Once this is merged I'll tag it as a nitrokey-v9, and we will be able to move on with tagging opcard and piv too, and add them to the firmware for the next testing release.

**Pull request merged**
