### PR TITLE
Merge upstream trussed.

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
AFAIS the only change that we have is removing the `default-syscalls` feature from the default features.
- We could try using upstream Trussed, at least until the next test release, as long as the CI works.
- If that does not work, I would prefer resetting the fork to upstream main and then cherry-picking the `default-syscalls` patch to keep the history clean.

**Comment by sosthene-nitrokey** [comment]
I know that's why the tags are there but I don't like the idea of overwriting main like this.

Is the history of this main branch really important? If all development is first merged upstream I don't think this branch will be used a lot for bisecting/blaming.

**Comment by robin-nitrokey** [comment]
It makes it easier to keep track of the delta.  Otherwise the comparison will show more and more merge commits and irrelevant changes.  Currently, it is not a big issue because we don’t have a big delta, but the more Nitrokey-only changes, the harder it will be to keep track.  (IMHO the comparison is quite readable currently only because we previously reset main about a year ago.)

So I’m fine with merging upstream right now, but I don’t think it’s sustainable in the long run.

What do you think of the following approach:
- Once Trussed 0.2.0 is released, we reset main to upstream/main.
- If we apply changes on top of v*x*.*y*.*z* (that would be tagged as v*x*.*y*.*z*-nitrokey.*n*), we create a branch v*x*.*y*.*z*-nitrokey that acts as our main branch for this set of changes.
- After a new upstream release, if we still need a patched version, we create a new fork branch from upstream/main.

This would mean that we don’t have to do hard resets, but it would also be easy to keep track of our changes in the fork.

**Comment by sosthene-nitrokey** [comment]
I like this idea of creating branches from trussed/main on top of which we cherry-pick our changes, rather than using main. That way there is no need to "erase" history.

**Review by robin-nitrokey — APPROVED** [review]

**Pull request merged**
