### PR TITLE
Add support for multiple backends

### PR DESCRIPTION
**Pull request by robin-nitrokey**
Open questions:

* we still use a `Vec<_, 2>` for backend selection – that is not flexible enough for the generic implementation
* naming: do we need the `Service` prefix? and the `ServiceBackends` enum should be singular, but that clashes with the `ServiceBackend` trait
* move the backend stuff into a `backend` module?

### CODE REVIEW

**Comment by sosthene-nitrokey** [comment]
> we still use a Vec<_, 2> for backend selection – that is not flexible enough for the generic implementation

`&'static [_]` could be a solution too.

**Comment by robin-nitrokey** [comment]
I also had that idea but discarded it as we cannot implement `serde::Deserialize` for static data.  But it looks like we don’t even need to implement that trait for the request types and it is derived unnecessarily so this could be a solution.

**Comment by sosthene-nitrokey** [comment]
It's weird that serde traits are implemented for the Request and Responses.

Another solution I could see is having the platform have a constant representing the number of backends that could then be passed to the ClientContext so that the Vec has exactly the right capacity.

**Comment by daringer** [comment]
* `Vec<>`-stuff, from my point of view it would be fine to set a proper upper limit here, not perfect but fine
* Naming: `ServiceBackend(s)` has grown historically, especially with this approach a more generic `Backend` might be the cleaner choice. But don't have a good solution for the naming clash  
* `backend` module? yes

**Comment by robin-nitrokey** [comment]
Replaced `Vec<_, _>` with `&'static [_]`.  This also allows us to avoid some clones and drop the `Clone` requirement for the backend type in many places.  (Or everywhere with `client-context-interchange`.)

**Comment by robin-nitrokey** [comment]
Updated to provide access to the `ServiceResources` to `ServiceBackend` implementors.

**Comment by robin-nitrokey** [comment]
Updated to move `B` into an associated type of `PollClient` and thereby removing it as a type parameter form all client traits.

**Comment by robin-nitrokey** [comment]
Open tasks:
- [ ] Investigate FIDO2 issues with usbip-runner
- [ ] Test backends with usbip-runner

**Comment by robin-nitrokey** [comment]
Upstreamed:
- https://github.com/trussed-dev/trussed/pull/67
- https://github.com/trussed-dev/trussed/pull/68

**Pull request closed without merging**
